# Generated by Django 5.2 on 2024-06-09


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('title', models.CharField(
                    help_text='Title or description of the task.',
                    max_length=255
                )),
                ('created', models.DateTimeField(
                    auto_now_add=True,
                    help_text='Timestamp when the task was created.'
                )),
                ('completed', models.BooleanField(
                    default=False,
                    help_text='Completion status of the task.'
                )),
            ],
        ),
    ]
